# Makefile.in generated by automake 1.13.4 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2013 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



# Process this file with automake to produce Makefile.in (in this,
# and all subdirectories).
# Makefile for the top-level directory of GNU hello.
#
# Copyright 1997, 1998, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2013,
# 2014 Free Software Foundation, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

# Copyright (C) 2004 Oren Ben-Kiki
# This file is distributed under the same terms as the Automake macro files.

# Generate automatic documentation using Doxygen. Goals and variables values
# are controlled by the various DX_COND_??? conditionals set by autoconf.
#
# The provided goals are:
# doxygen-doc: Generate all doxygen documentation.
# doxygen-run: Run doxygen, which will generate some of the documentation
#              (HTML, CHM, CHI, MAN, RTF, XML) but will not do the post
#              processing required for the rest of it (PS, PDF, and some MAN).
# doxygen-man: Rename some doxygen generated man pages.
# doxygen-ps: Generate doxygen PostScript documentation.
# doxygen-pdf: Generate doxygen PDF documentation.
#
# Note that by default these are not integrated into the automake goals. If
# doxygen is used to generate man pages, you can achieve this integration by
# setting man3_MANS to the list of man pages generated and then adding the
# dependency:
#
#   $(man3_MANS): doxygen-doc
#
# This will cause make to run doxygen and generate all the documentation.
#
# The following variable is intended for use in Makefile.am:
#
# DX_CLEANFILES = everything to clean.
#
# This is usually added to MOSTLYCLEANFILES.

am__is_gnu_make = test -n '$(MAKEFILE_LIST)' && test -n '$(MAKELEVEL)'
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/opalrivet
pkgincludedir = $(includedir)/opalrivet
pkglibdir = $(libdir)/opalrivet
pkglibexecdir = $(libexecdir)/opalrivet
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
DIST_COMMON = $(srcdir)/Makefile.syst $(srcdir)/Makefile.software \
	$(srcdir)/m4/aminclude.am INSTALL NEWS README AUTHORS \
	ChangeLog $(srcdir)/Makefile.in $(srcdir)/Makefile.am \
	$(top_srcdir)/configure $(am__configure_deps) \
	$(srcdir)/config.h.in COPYING config.guess config.sub \
	install-sh missing ltmain.sh
subdir = .
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_check_compile_flag.m4 \
	$(top_srcdir)/m4/libtool.m4 $(top_srcdir)/m4/ltoptions.m4 \
	$(top_srcdir)/m4/ltsugar.m4 $(top_srcdir)/m4/ltversion.m4 \
	$(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/m4_ax_prog_doxygen.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DIST_SOURCES =
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) \
	$(LISP)config.h.in
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
CSCOPE = cscope
AM_RECURSIVE_TARGETS = cscope
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
am__post_remove_distdir = $(am__remove_distdir)
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
DIST_TARGETS = dist-gzip
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/andriish/Projects/opalrivet/trunk/missing aclocal-1.13
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 1
AR = ar
AUTOCONF = ${SHELL} /home/andriish/Projects/opalrivet/trunk/missing autoconf
AUTOHEADER = ${SHELL} /home/andriish/Projects/opalrivet/trunk/missing autoheader
AUTOMAKE = ${SHELL} /home/andriish/Projects/opalrivet/trunk/missing automake-1.13
AWK = gawk
CC = gcc
CCDEPMODE = depmode=none
CFLAGS = -g -O2 -fdiagnostics-color=never -Wextra
CPP = gcc -E
CPPFLAGS = 
CXX = g++  -Wextra -Wall -pedantic -Wno-long-long -Wno-variadic-macros
CXXCPP = g++ -E
CXXDEPMODE = depmode=none
CXXFLAGS = -g -O2 -fdiagnostics-color=never -Wextra -Wno-long-long -Wall -Werror -pedantic -Wno-error=long-long
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DOXYGEN_PAPER_SIZE = 
DSYMUTIL = 
DUMPBIN = 
DX_CONFIG = Doxyfile
DX_DOCDIR = ./doc
DX_DOT = 
DX_DOXYGEN = /usr/bin/doxygen
DX_DVIPS = 
DX_EGREP = /usr/bin/egrep
DX_ENV =  SRCDIR='.' PROJECT='opalrivet' DOCDIR='./doc' VERSION='0.290M' PERL_PATH='/usr/bin/perl' HAVE_DOT='NO' GENERATE_MAN='NO' GENERATE_RTF='NO' GENERATE_XML='NO' GENERATE_HTMLHELP='NO' GENERATE_CHI='NO' GENERATE_HTML='NO' GENERATE_LATEX='YES'
DX_FLAG_chi = 0
DX_FLAG_chm = 0
DX_FLAG_doc = 1
DX_FLAG_dot = 0
DX_FLAG_html = 0
DX_FLAG_man = 0
DX_FLAG_pdf = 1
DX_FLAG_ps = 0
DX_FLAG_rtf = 0
DX_FLAG_xml = 0
DX_HHC = 
DX_LATEX = 
DX_MAKEINDEX = /usr/bin/makeindex
DX_PDFLATEX = /usr/bin/pdflatex
DX_PERL = /usr/bin/perl
DX_PROJECT = opalrivet
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
F77 = g77
FFLAGS = -g -O2
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/andriish/Projects/opalrivet/trunk/missing makeinfo
MANIFEST_TOOL = :
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OPALRIVET_API_VERSION = 0.290M
OPALRIVET_SO_VERSION = 0:0:0
OTOOL = 
OTOOL64 = 
PACKAGE = opalrivet
PACKAGE_BUGREPORT = andrii.verbytskyi@desy.de
PACKAGE_NAME = opalrivet
PACKAGE_STRING = opalrivet 0.290M
PACKAGE_TARNAME = opalrivet
PACKAGE_URL = http://mpp.mpg.de
PACKAGE_VERSION = 0.290M
PATH_SEPARATOR = :
RANLIB = ranlib
ROOT_CFLAGS = -pthread -m64 -I/usr/include/root
ROOT_LIBS = -L/usr/lib64/root -lCore -lCint -lRIO -lNet -lHist -lGraf -lGraf3d -lGpad -lTree -lRint -lPostscript -lMatrix -lPhysics -lMathCore -lThread -pthread -lm -ldl -rdynamic -lMinuit 
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
VERSION = 0.290M
abs_builddir = /home/andriish/Projects/opalrivet/trunk
abs_srcdir = /home/andriish/Projects/opalrivet/trunk
abs_top_builddir = /home/andriish/Projects/opalrivet/trunk
abs_top_srcdir = /home/andriish/Projects/opalrivet/trunk
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
ac_ct_F77 = g77
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/andriish/Projects/opalrivet/trunk/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
AUTOMAKE_OPTIONS = subdir-objects check-news gnu
AM_CFLAGS = 
# -Wno-long-long -Wall -Wextra   -Werror -pedantic -Wno-error=long-long 
AM_CXXFLAGS = 
#-Wno-long-long -Wall -Wextra   -Werror -pedantic -Wno-error=long-long 

#ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS} -I .
#ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS}   -I .
ACLOCAL_AMFLAGS = ${ACLOCAL_FLAGS} -I m4
AM_CPPFLAGS = -Ilib -I$(top_srcdir)/lib -Isrc -I$(top_srcdir)/src

#export X509_USER_PROXY=$(pwd)/k5-ca-proxy.pem
#GEN=sherpa
#GEN=herwig++
#GEN=pythia8

#GEN=evtgen
#GEN?=pythia8
#GEN=pythia8_evtgen
#CUTS?=central
NAME = JADE_OPAL_2000_S4300807a
ARCH = $(shell uname -m)
MNT = 
_TOPDIR = $(PWD)/rpmbuild
_INSTALLDIR = $(PWD)/install
YODA_VERS = 1.4.0
RIVET_VERS = 2.3.0
PHOTOS_VERS = 3.54
TAUOLA_VERS = 1.1.4
SHERPA_VERS = 2.1.1
FASTJET_VERS = 3.1.2
HEPMC_VERS = 2.06.09
#PYTHIA8_VERS=8180
PYTHIA8_VERS = 8205
THEPEG_VERS = 1.9.0
HERWIG_PLUSPLUSVERS = 2.7.0
CYTHON_VERS = 0.19
AGILE_VERS = 1.4.1
SOURCES = src/Helpers.cxx         src/Helpers.h \
		src/Cuts.cxx            src/Cuts.h \
		src/TSampleInfo.cxx     src/TSampleInfo.h \
		src/OPALJet.cxx        src/OPALJet.h  \
		src/TAdvancedGraph.cxx  src/TAdvancedGraph.h \
		src/TUserProofData.cxx 	src/TUserProofData.h

MOSTLYCLEANFILES = $(DX_CLEANFILES)
#DX_CLEAN_HTML = ./doc/html
#DX_CLEAN_CHM = ./doc/chm
##DX_CLEAN_CHI = ./doc/opalrivet.chi
#DX_CLEAN_MAN = ./doc/man
#DX_CLEAN_RTF = ./doc/rtf
#DX_CLEAN_XML = ./doc/xml
#DX_CLEAN_PS = ./doc/opalrivet.ps
#DX_PS_GOAL = doxygen-ps
DX_CLEAN_PDF = ./doc/opalrivet.pdf
DX_PDF_GOAL = doxygen-pdf
DX_CLEAN_LATEX = ./doc/latex
DX_CLEANFILES = \
    ./doc/opalrivet.tag \
    -r \
    $(DX_CLEAN_HTML) \
    $(DX_CLEAN_CHM) \
    $(DX_CLEAN_CHI) \
    $(DX_CLEAN_MAN) \
    $(DX_CLEAN_RTF) \
    $(DX_CLEAN_XML) \
    $(DX_CLEAN_PS) \
    $(DX_CLEAN_PDF) \
    $(DX_CLEAN_LATEX)

EXTRA_DIST = Doxyfile
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am $(srcdir)/Makefile.syst $(srcdir)/Makefile.software $(srcdir)/m4/aminclude.am $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --gnu'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --gnu \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --gnu Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --gnu Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;
$(srcdir)/Makefile.syst $(srcdir)/Makefile.software $(srcdir)/m4/aminclude.am:

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs

distclean-libtool:
	-rm -f libtool config.lt

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscope: cscope.files
	test ! -s cscope.files \
	  || $(CSCOPE) -b -q $(AM_CSCOPEFLAGS) $(CSCOPEFLAGS) -i cscope.files $(CSCOPE_ARGS)
clean-cscope:
	-rm -f cscope.files
cscope.files: clean-cscope cscopelist
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
	-rm -f cscope.out cscope.in.out cscope.po.out cscope.files

distdir: $(DISTFILES)
	@case `sed 15q $(srcdir)/NEWS` in \
	*"$(VERSION)"*) : ;; \
	*) \
	  echo "NEWS not updated; not releasing" 1>&2; \
	  exit 1;; \
	esac
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__post_remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__post_remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__post_remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__post_remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__post_remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__post_remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__post_remove_distdir)

dist dist-all:
	$(MAKE) $(AM_MAKEFLAGS) $(DIST_TARGETS) am__post_remove_distdir='@:'
	$(am__post_remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir)
	chmod u+w $(distdir)
	mkdir $(distdir)/_build $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__post_remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
check: check-am
all-am: Makefile config.h
installdirs:
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-generic clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -f Makefile
distclean-am: clean-am distclean-generic distclean-hdr \
	distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am:

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am:

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-generic mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-local

.MAKE: all install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am am--refresh check check-am clean \
	clean-cscope clean-generic clean-libtool cscope cscopelist-am \
	ctags ctags-am dist dist-all dist-bzip2 dist-gzip dist-lzip \
	dist-shar dist-tarZ dist-xz dist-zip distcheck distclean \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-data install-data-am install-dvi install-dvi-am \
	install-exec install-exec-am install-html install-html-am \
	install-info install-info-am install-man install-pdf \
	install-pdf-am install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-local

#CXX?='g++ -Wextra -Wall -pedantic -Wno-long-long -Wno-variadic-macros'

warn: 
	echo 'ARE YOU SURE?'

all:	 		    output/$(GEN)_91_$(CUTS).root \
					output/opal_9196_$(CUTS).root \
					output/opal_9197_$(CUTS).root \
					output/opal_9198_$(CUTS).root \
					output/opal_9199_$(CUTS).root \
					output/opal_9100_$(CUTS).root \
					output/opal_130_$(CUTS).root output/$(GEN)_130.root \
					output/opal_136_$(CUTS).root output/$(GEN)_136.root \
					output/opal_161_$(CUTS).root output/$(GEN)_161.root \
					output/opal_172_$(CUTS).root output/$(GEN)_172.root \
					output/opal_183_$(CUTS).root output/$(GEN)_183.root \
					output/opal_189_$(CUTS).root output/$(GEN)_189.root \
					output/opal_192_$(CUTS).root output/$(GEN)_192.root \
					output/opal_196_$(CUTS).root output/$(GEN)_196.root \
					output/opal_202_$(CUTS).root output/$(GEN)_202.root \
					output/opal_205_$(CUTS).root output/$(GEN)_205.root \
					output/opal_207_$(CUTS).root output/$(GEN)_207.root

allmc:
	 		    output/$(GEN)_91.root \
					output/$(GEN)_130.root \
					output/$(GEN)_136.root \
					output/$(GEN)_161.root \
					output/$(GEN)_172.root \
					output/$(GEN)_183.root \
					output/$(GEN)_189.root \
					output/$(GEN)_192.root \
					output/$(GEN)_196.root \
					output/$(GEN)_202.root \
					output/$(GEN)_205.root \
					output/$(GEN)_207.root

alldata:			\
					output/opal_9196_$(CUTS).root \
					output/opal_9197_$(CUTS).root \
					output/opal_9198_$(CUTS).root \
					output/opal_9199_$(CUTS).root \
					output/opal_9100_$(CUTS).root \
					output/opal_130_$(CUTS).root \
					output/opal_136_$(CUTS).root \
					output/opal_161_$(CUTS).root \
					output/opal_172_$(CUTS).root \
					output/opal_183_$(CUTS).root \
					output/opal_189_$(CUTS).root \
					output/opal_192_$(CUTS).root \
					output/opal_196_$(CUTS).root \
					output/opal_202_$(CUTS).root \
					output/opal_205_$(CUTS).root \
					output/opal_207_$(CUTS).root

src_Rivet: external/Rivet-$(RIVET_VERS).tar.gz

external/Rivet-$(RIVET_VERS).tar.gz:
		wget http://www.hepforge.org/archive/rivet/Rivet-$(RIVET_VERS).tar.gz -O external/Rivet-$(RIVET_VERS).tar.gz

src_TAUOLA: external/TAUOLA-$(TAUOLA_VERS).tar.gz external/patch-TAUOLA-0.txt 
external/TAUOLA-$(TAUOLA_VERS).tar.gz:
		wget http://tauolapp.web.cern.ch/tauolapp/resources/TAUOLA.$(TAUOLA_VERS)/TAUOLA.$(TAUOLA_VERS).tar.gz
		tar xvfz TAUOLA.$(TAUOLA_VERS).tar.gz
		mv TAUOLA TAUOLA-$(TAUOLA_VERS)
		tar cvf external/TAUOLA-$(TAUOLA_VERS).tar.gz TAUOLA-$(TAUOLA_VERS)
		rm -rf TAUOLA.$(TAUOLA_VERS).tar.gz

src_PHOTOS: external/PHOTOS-$(PHOTOS_VERS).tar.gz external/patch-PHOTOS-0.txt 
external/PHOTOS-$(PHOTOS_VERS).tar.gz:
		wget http://photospp.web.cern.ch/photospp/resources/PHOTOS.$(PHOTOS_VERS)/PHOTOS.$(PHOTOS_VERS).tar.gz
		tar xvfz PHOTOS.$(PHOTOS_VERS).tar.gz
		mv PHOTOS PHOTOS-$(PHOTOS_VERS)
		tar cvf external/PHOTOS-$(PHOTOS_VERS).tar.gz PHOTOS-$(PHOTOS_VERS)
		rm -rf PHOTOS.$(PHOTOS_VERS).tar.gz

src_EvtGen: external/EvtGen-1.3.0.tar.gz  external/patch-EvtGen-0.txt 
external/EvtGen-1.3.0.tar.gz:
		svn export http://svn.cern.ch/guest/evtgen/tags/R01-03-00 EvtGen --force
		rm -rf EvtGen-1.3.0
		mkdir -p EvtGen-1.3.0
		mv EvtGen/* EvtGen-1.3.0
		cp external/EvtGen/* EvtGen-1.3.0
		tar cvf external/EvtGen-1.3.0.tar.gz EvtGen-1.3.0
		rm -rf EvtGen.R01-03-00.tar.gz EvtGen

src_HepMC: external/HepMC-$(HEPMC_VERS).tar.gz   external/HepMC-examples-hwaend.patch external/HepMC-examples-makefile.patch external/HepMC-fix-typo-hierachy-hierarchy.patch external/HepMC-linking.patch

external/HepMC-$(HEPMC_VERS).tar.gz: 
		wget http://lcgapp.cern.ch/project/simu/HepMC/download/HepMC-$(HEPMC_VERS).tar.gz -O external/HepMC-$(HEPMC_VERS).tar.gz

src_YODA: external/YODA-$(YODA_VERS).tar.gz

external/YODA-$(YODA_VERS).tar.gz: 
		rm -rf YODA-$(YODA_VERS)
		hg clone http://yoda.hepforge.org/hg/yoda YODA-$(YODA_VERS)
		tar cf YODA-$(YODA_VERS).tar YODA-$(YODA_VERS)
		gzip YODA-$(YODA_VERS).tar
		mv YODA-$(YODA_VERS).tar.gz external/
		rm -rf YODA-$(YODA_VERS)

src_fastjet: external/fastjet-$(FASTJET_VERS).tar.gz
external/fastjet-$(FASTJET_VERS).tar.gz: 
		wget http://www.fastjet.fr/repo/fastjet-$(FASTJET_VERS).tar.gz -O external/fastjet-$(FASTJET_VERS).tar.gz

src_pythia8: external/pythia$(PYTHIA8_VERS).tgz  external/pythia8-fix-soname.patch external/pythia8-hepmc-version.patch external/pythia8-xmldir.patch
external/pythia$(PYTHIA8_VERS).tgz:
		wget http://home.thep.lu.se/~torbjorn/pythia8/pythia$(PYTHIA8_VERS).tgz -O external/pythia$(PYTHIA8_VERS).tgz

src_SHERPA-MC: external/SHERPA-MC-$(SHERPA_VERS).tar.gz
external/SHERPA-MC-$(SHERPA_VERS).tar.gz:
		wget http://www.hepforge.org/archive/sherpa/SHERPA-MC-$(SHERPA_VERS).tar.gz -O external/SHERPA-MC-$(SHERPA_VERS).tar.gz

src_ThePEG: external/ThePEG-$(THEPEG_VERS).tar.bz2 external/patch-ThePEG-0.txt
external/ThePEG-$(THEPEG_VERS).tar.bz2:
		wget http://www.hepforge.org/archive/thepeg/ThePEG-$(THEPEG_VERS).tar.bz2 -O external/ThePEG-$(THEPEG_VERS).tar.bz2

src_Herwig++: external/Herwig++-$(HERWIG_PLUSPLUSVERS).tar.bz2
external/Herwig++-$(HERWIG_PLUSPLUSVERS).tar.bz2:
	wget http://www.hepforge.org/archive/herwig/Herwig++-$(HERWIG_PLUSPLUSVERS).tar.bz2 -O external/Herwig++-$(HERWIG_PLUSPLUSVERS).tar.bz2

src_Cython: external/Cython-$(CYTHON_VERS).tar.gz
external/Cython-$(CYTHON_VERS).tar.gz:
	wget http://www.cython.org/release/Cython-$(CYTHON_VERS).tar.gz -O external/Cython-$(CYTHON_VERS).tar.gz

src_AGILe: external/AGILe-$(AGILE_VERS).tar.gz
external/AGILe-$(AGILE_VERS).tar.gz:
	wget http://www.hepforge.org/archive/agile/AGILe-$(AGILE_VERS).tar.gz -O external/AGILe-$(AGILE_VERS).tar.gz

srcrpm_%: src_%   external/%.spec
	cp   external/$**{.tar.gz,.tar.bz2,tgz} $(_TOPDIR)/SOURCES/    || exit 0
	cp  external/*patch* $(_TOPDIR)/SOURCES/
	rpmbuild -D '%_topdir '$(_TOPDIR) -bs external/$*.spec

binrpm_%: srcrpm_%
		rpmbuild -D '%_topdir '$(_TOPDIR) --rebuild $(_TOPDIR)/SRPMS/$**

srcrpm_YODA: src_YODA
	cp   external/YODA*.tar.gz $(_TOPDIR)/SOURCES/
	cp external/patch-YODA-*.txt $(_TOPDIR)/SOURCES/
	rpmbuild -D '%_topdir '$(_TOPDIR) -bs external/YODA.spec

Rivetpatchold: src_Rivet
	rm -rf external/Rivet-$(RIVET_VERS)
	rm -rf external/Rivet-$(RIVET_VERS)_orig	
	tar -zxf  external/Rivet-$(RIVET_VERS).tar.gz -C external
	cp -r external/Rivet-$(RIVET_VERS) external/Rivet-$(RIVET_VERS)_orig	
	rm -rf patch-Rivet-*.txt
	cp -R external/Rivet/* external/Rivet-$(RIVET_VERS)/

	diff -Naur  -x   *RivetPaths.* -x *rivet.pxd* external/Rivet-$(RIVET_VERS)_orig  external/Rivet-$(RIVET_VERS) > external/patch-Rivet-0.txt  || exit 0
	diff -Naur                                    external/Rivet-$(RIVET_VERS)_orig/src/Tools/RivetPaths.cc  external/Rivet-$(RIVET_VERS)/src/Tools/RivetPaths.cc > external/patch-Rivet-1.txt || exit 0
	diff -Naur                                    external/Rivet-$(RIVET_VERS)_orig/src/Tools/RivetPaths.cc  external/Rivet-$(RIVET_VERS)/src/Tools/RivetPaths.cc >> external/patch-Rivet-1.txt || exit 0
	diff -Naur                                    external/Rivet-$(RIVET_VERS)_orig/include/Rivet/Tools/RivetPaths.hh  external/Rivet-$(RIVET_VERS)/include/Rivet/Tools/RivetPaths.hh >> external/patch-Rivet-1.txt || exit 0
	diff -Naur                                    external/Rivet-$(RIVET_VERS)_orig//pyext/rivet/rivet.pxd  external/Rivet-$(RIVET_VERS)/pyext/rivet/rivet.pxd >> external/patch-Rivet-1.txt || exit 0
	sed -i 's@external/Rivet-$(RIVET_VERS)_orig@.@g' external/patch-Rivet-*.txt
	sed -i 's@external/Rivet-$(RIVET_VERS)@.@g'      external/patch-Rivet-*.txt

Rivetpatch: src_Rivet
	rm -rf external/Rivet-$(RIVET_VERS)
	rm -rf external/Rivet-$(RIVET_VERS)_orig	
	tar -zxf  external/Rivet-$(RIVET_VERS).tar.gz -C external
	cp -r external/Rivet-$(RIVET_VERS) external/Rivet-$(RIVET_VERS)_orig	
	rm -rf patch-Rivet-*.txt
	cp -R external/Rivet/* external/Rivet-$(RIVET_VERS)/

	diff -Naur                                    external/Rivet-$(RIVET_VERS)_orig/include/Rivet/Tools/RivetBoost.hh  external/Rivet-$(RIVET_VERS)/include/Rivet/Tools/RivetBoost.hh > external/patch-Rivet-0.txt || exit 0
	sed -i 's@external/Rivet-$(RIVET_VERS)_orig@.@g' external/patch-Rivet-*.txt
	sed -i 's@external/Rivet-$(RIVET_VERS)@.@g'      external/patch-Rivet-*.txt

srcrpm_Rivet: src_Rivet Rivetpatch
	cp   external/Rivet*.tar.gz $(_TOPDIR)/SOURCES/
	cp external/patch-Rivet-*.txt $(_TOPDIR)/SOURCES/
	rpmbuild -D '%_topdir '$(_TOPDIR) -bs external/Rivet.spec

binrpm_Rivet:  srcrpm_Rivet external/Rivet.spec install_HepMC   install_YODA  install_fastjet
	$(shell export PATH=$(_INSTALLDIR):$$PATH; export FASTJETPATH=$(_INSTALLDIR); export YODAPATH=$(_INSTALLDIR); export HEPMCPATH=$(_INSTALLDIR); rpmbuild -D '%_topdir '$(_TOPDIR) --rebuild $(_TOPDIR)/SRPMS/Rivet-$(RIVET_VERS)*   )

binrpm_pythia8:  srcrpm_pythia8 external/pythia8.spec install_HepMC  
	$(shell export PATH=$(_INSTALLDIR):$$PATH; export HEPMC2=$(_INSTALLDIR); rpmbuild -D '%_topdir '$(_TOPDIR) --rebuild $(_TOPDIR)/SRPMS/pythia8-*   )

########################################################################

#allbinrpm:  binrpm_HepMC   binrpm_YODA  binrpm_fastjet binrpm_Rivet binrpm_Cython  binrpm_AGILe  binrpm_PHOTOS binrpm_TAUOLA binrpm_Herwig++ binrpm_ThePEG

install_%: binrpm_%
	rpm -Uvh --nodeps --force $(_TOPDIR)/RPMS/*/$** --prefix=$(_INSTALLDIR)

localsystem: dirs src_Rivet

.PHONY: dirs

dirs:
	mkdir -p $(_TOPDIR)
	mkdir -p $(_TOPDIR)/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
	mkdir -p ./bin/$(ARCH)
	mkdir -p ./obj/$(ARCH)
	mkdir -p ./lib/$(ARCH)
	mkdir -p output
	mkdir -p obj
	mkdir -p tmp
	mkdir -p gen
	mkdir -p run
	mkdir -p logs
	mkdir -p subs_output

gen/%LinkDef.h: dirs
	@rm -f gen/$*LinkDef.h
	@echo  "#ifdef __MAKECINT__"   >> gen/$*LinkDef.h
	@echo  "#pragma link C++ class "$*"+;"   >> gen/$*LinkDef.h
	@echo  "#endif"      >> gen/$*LinkDef.h

gen/%Dict.cxx: dirs src/%.h gen/%LinkDef.h
	echo "Generating dictionary $@..."
	rootcint -f $@ -c  src/$*.h gen/$*LinkDef.h

output/opal_%.root:   dirs $(SOURCES)    bin/$(ARCH)/create_proof       src/opalanalysis.C gen/DB.root
		bin/$(ARCH)/create_proof  LOCAL_OPAL_$* share/input.rc

output/$(GEN)_%.root: dirs $(SOURCES)	 bin/$(ARCH)/opal$(GEN) run/Run$(GEN).dat_%  run/Makefile external/Rivet/src/Analyses/JADE_OPAL_2000_S4300807a.cc
		make -C run GEN=$(GEN) ENERGY=$*
		mv run/*.root ./output

run/Runpythia8.dat_%: 	bin/$(ARCH)/opal$(GEN)
		mkdir -p run		
		cp share/Runpythia8.dat run/Runpythia8.dat_$*		
		sed -i 's@.*Beams:eCM.*@Beams:eCM = '$(shell echo  1.0*$* | bc -qi | tail -n 1)'@g' run/Runpythia8.dat_$*

run/Runpythia8_nohad.dat_%: share/Runpythia8_nohad.dat
		cp share/Runpythia8_nohad.dat run/Runpythia8_nohad.dat		
		sed -i 's@.*Beams:eCM.*@Beams:eCM = '$(shell echo  1.0*$* | bc -qi | tail -n 1)'@g' run/Runpythia8_nohad.dat_$*

run/Runpythia8_evtgen.dat_%: share/Runpythia8_evtgen.dat
		cp share/Runpythia8_evtgen.dat run/Runpythia8_evtgen.dat_$*		
		sed -i 's@.*Beams:eCM.*@Beams:eCM = '$(shell echo  1.0*$* | bc -qi | tail -n 1)'@g' run/Runpythia8_evtgen.dat_$*

run/Runsherpa.dat_%: share/Runsherpa.dat
		cp share/Runsherpa.dat run/Runsherpa.dat_$*
		sed -i 's@.*BEAM_ENERGY_1.*@BEAM_ENERGY_1 = '$(shell echo  0.5*$* | bc -qi | tail -n 1)';@g' run/Runsherpa.dat_$*
		sed -i 's@.*BEAM_ENERGY_2.*@BEAM_ENERGY_2 = '$(shell echo  0.5*$* | bc -qi | tail -n 1)';@g' run/Runsherpa.dat_$*

run/Runherwig++.dat_%: share/Runherwig++.dat
		cp share/Runherwig++.dat run/Runherwig++.dat_$*
		sed -i 's@.*set LEPGenerator:EventHandler:LuminosityFunction:Energy.*@set LEPGenerator:EventHandler:LuminosityFunction:Energy '$(shell echo  1.0*$* | bc -qi | tail -n 1)'@g' run/Runherwig++.dat_$*

run/Runevtgen.dat_%: share/Runevtgen.dat		
		cp share/Runevtgen.dat run/Runevtgen.dat_$*

run/Makefile: share/Makefile.run		
		cp share/Makefile.run run/Makefile

beauty:
		astyle -n --keep-one-line-blocks --style=gnu    ./*/*.h   ./*/*.cxx ./*/*.C ./*/*.hh

bin/$(ARCH)/opal$(GEN):
	rm -f bin/$(ARCH)/opal$(GEN)
	touch bin/$(ARCH)/opal$(GEN)

obj/$(ARCH)/opalpythia8.o:  dirs src/MC/opalpythia8.cxx
	$(CXX) -fdiagnostics-color=never   -pipe  -c src/MC/opalpythia8.cxx -o obj/$(ARCH)/opalpythia8.o 

bin/$(ARCH)/opalpythia8:  dirs obj/$(ARCH)/opalpythia8.o
	$(CXX) -fdiagnostics-color=never   -pipe   -lpythia8 -lpythia8tohepmc -lHepMC obj/$(ARCH)/opalpythia8.o -o ./bin/$(ARCH)/opalpythia8  -L/lib64

bin/$(ARCH)/opalpythia8_nohad:  dirs obj/$(ARCH)/opalpythia8.o
	$(CXX) -fdiagnostics-color=never   -pipe   -lpythia8 -lpythia8tohepmc -lHepMC obj/$(ARCH)/opalpythia8.o -o ./bin/$(ARCH)/opalpythia8_nohad  -L/lib64

obj/$(ARCH)/opalpythia8_evtgen.o:  dirs src/MC/opalpythia8_evtgen.cxx
	$(CXX) -fdiagnostics-color=never   -pipe  -c src/MC/opalpythia8_evtgen.cxx -o obj/$(ARCH)/opalpythia8_evtgen.o -L/lib64 

bin/$(ARCH)/opalpythia8_evtgen:  dirs obj/$(ARCH)/opalpythia8_evtgen.o
	$(CXX) -fdiagnostics-color=never   -pipe  -lpythia8 -lHepMC  -lEvtGenExternal  obj/$(ARCH)/opalpythia8_evtgen.o -o ./bin/$(ARCH)/opalpythia8_evtgen -L/lib64

obj/$(ARCH)/opalevtgen.o:  dirs src/opalevtgen.cxx
	$(CXX) -fdiagnostics-color=never   -pipe  $(shell root-config --cflags) -c src/opalevtgen.cxx -o obj/$(ARCH)/opalevtgen.o

bin/$(ARCH)/opalevtgen:  dirs obj/$(ARCH)/opalevtgen.o
	$(CXX) -fdiagnostics-color=never   -pipe   -lEvtGenExternal $(shell  root-config --libs)  obj/$(ARCH)/opalevtgen.o -o ./bin/$(ARCH)/opalevtgen   -L/lib64

bin/$(ARCH)/create_proof: dirs src/create_proof.cxx  src/Helpers.cxx src/Helpers.h gen/TSampleInfoDict.cxx src/TSampleInfo.cxx
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -g -DSIMPLE_HELPERS_ONLY $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src/create_proof.cxx  src/Helpers.cxx  gen/TSampleInfoDict.cxx src/TSampleInfo.cxx -o ./bin/$(ARCH)/create_proof

bin/$(ARCH)/create_DB: dirs src/create_DB.cxx gen/TSampleInfoDict.cxx $(SOURCES)
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -g -DSIMPLE_HELPERS_ONLY $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src/create_DB.cxx  src/Helpers.cxx gen/TSampleInfoDict.cxx src/TSampleInfo.cxx  -o ./bin/$(ARCH)/create_DB

gen/DB.root: dirs bin/$(ARCH)/create_DB
	bin/$(ARCH)/create_DB  gen/DB.root $(MNT)/scratch/andriish/opal/ntuple_root/qcd/

bin/$(ARCH)/create_plots: dirs src//create_plots.cxx src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src//create_plots.cxx src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o ./bin/$(ARCH)/create_plots

bin/$(ARCH)/create_specialplots: dirs src//create_specialplots.cxx src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src//create_specialplots.cxx src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o ./bin/$(ARCH)/create_specialplots

bin/$(ARCH)/create_tables: dirs src//create_tables.cxx src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src//create_tables.cxx src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o ./bin/$(ARCH)/create_tables

bin/$(ARCH)/create_manip: dirs src//create_manip.cxx src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src//create_manip.cxx src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o ./bin/$(ARCH)/create_manip

bin/$(ARCH)/create_old: dirs src//create_old.cxx src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -fdiagnostics-color=never  -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src//create_old.cxx src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o ./bin/$(ARCH)/create_old

lib/$(ARCH)/libopal.so:  dirs  src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h  gen/TAdvancedGraphLinkDef.h
	$(CXX) -fdiagnostics-color=never -Wextra -Wall -pedantic -Wno-long-long -Wno-variadic-macros -g -shared -fPIC -pipe  -I. -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof   src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o lib/$(ARCH)/libopal.so
	rlibmap -f -o lib/$(ARCH)/libopal.rootmap -l lib/$(ARCH)/libopal.so  -c gen/TAdvancedGraphLinkDef.h

.rootrc: lib/$(ARCH)/libopal.so
	echo Unix.*.Root.DynamicPath:  .:./lib/$(ARCH):$(shell root-config --libdir) > .rootrc
	echo Rint.Logon: ./rootlogon.C >> .rootrc
	echo 'rootlogon(){ gROOT->ProcessLine(".L ./lib/'$(ARCH)'/libopal.so");}' >./rootlogon.C

output/plots_%.root: .rootrc dirs   bin/$(ARCH)/create_plots output/opal_%.root output/$(GEN)_%.root output/shapemanip_%.root output/old_%.root
	bin/$(ARCH)/create_plots $* output/opal_$*.root output/$(GEN)_$*.root output/shapemanip_$*.root output/old_$*.root

output/tables_%.tex: .rootrc dirs   bin/$(ARCH)/create_tables 
	bin/$(ARCH)/create_tables  output/plots_$*.root  output/tables_$*.tex

doc/opalanalysis.pdf:  doc/opalanalysis.tex
		$(MAKE) $(shell cat doc/opalanalysis.tex | grep output/tables | sed 's@\input{../@@g' | grep -v '%' | sed 's@}@@g' )
		pdflatex doc/opalanalysis.tex
		mv opalanalysis.pdf  doc/opalanalysis.pdf

#pdf-local: doc/opalanalysis.pdf

bin/$(ARCH)/hepplotconvert: dirs   external/hepplotconvert/WriterROOT.h external/hepplotconvert/ROOTConvert.cc external/hepplotconvert/ROOTConvert.h external/hepplotconvert/ReaderROOT.cc external/hepplotconvert/ReaderROOT.h external/hepplotconvert/hepplotconvert.cxx external/hepplotconvert/WriterROOT.cc
		$(CXX) -fdiagnostics-color=never   -pipe  -fdiagnostics-color=never  -I. -g -fdiagnostics-color=never  $(shell  yoda-config --ldflags --libs --cflags  )  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  external/hepplotconvert/WriterROOT.h external/hepplotconvert/ROOTConvert.cc external/hepplotconvert/ROOTConvert.h external/hepplotconvert/ReaderROOT.cc external/hepplotconvert/ReaderROOT.h external/hepplotconvert/hepplotconvert.cxx external/hepplotconvert/WriterROOT.cc -o ./bin/$(ARCH)/hepplotconvert

output/JADE_OPAL_2000_S4300807.root: bin/$(ARCH)/hepplotconvert external/Rivet/data/refdata/JADE_OPAL_2000_S4300807a.yoda
	bin/$(ARCH)/hepplotconvert yoda2root external/Rivet/data/refdata/JADE_OPAL_2000_S4300807a.yoda output/JADE_OPAL_2000_S4300807.root

output/old_%.root: dirs bin/$(ARCH)/create_old output/JADE_OPAL_2000_S4300807.root
	bin/$(ARCH)/create_old   output/old_$*.root nevermind output/JADE_OPAL_2000_S4300807.root

output/shapemanip_%.root: dirs bin/$(ARCH)/create_manip  output/shape_%.root  .rootrc
	mkdir -p subs_output
	external/cppshape/examples/shape/bin/shape2 P output/shape_$* external/cppshape/examples/shape/QCDadmin/QCDadmin_200_$*.txt
	h2root  output/shape_$*_manip.rzhist
	h2root  output/shape_$*.rzhist
	bin/$(ARCH)/create_manip   tmp/shapemanip_$*_durham.root durham output/shape_$*_manip.root output/shape_$*.root
	bin/$(ARCH)/create_manip   tmp/shapemanip_$*_antikt.root antikt output/shape_$*_manip.root output/shape_$*.root
	hadd -f output/shapemanip_$*.root tmp/shapemanip_$*_antikt.root tmp/shapemanip_$*_durham.root

output/shape_%.root:
				make -C external/cppshape clean
				make -C external/cppshape/examples/shape clean
				make -C external/cppshape
				make -C external/cppshape/examples/shape
			    rm -rf output_200_$*.rzhist
			    external/cppshape/examples/shape/bin/shape2 A /scratch/andriish/opal/ntuple/qcd/  external/cppshape/examples/shape/QCDadmin/QCDadmin_200_$*.txt
				mv  output_200_$*.rzhist output/shape_$*.rzhist
				h2root output/shape_$*.rzhist

bin/$(ARCH)/create_systematics: dirs src//create_systematics.cxx src/Helpers.cxx src/Helpers.h gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx src/TAdvancedGraph.h
		$(CXX) -fdiagnostics-color=never   -pipe  -I. -Isrc -I../ -g  $(shell  root-config --ldflags --glibs --cflags  ) -L$(shell root-config --config | sed 's@\ @\n@g' | grep "\-\-libdir=" | cut -f 2 -d=) -lProof  src//create_systematics.cxx src/Helpers.cxx  gen/TAdvancedGraphDict.cxx src/TAdvancedGraph.cxx -o ./bin/$(ARCH)/create_systematics

uclean:
	rm -rf output/*
	rm -rf subs_output/*	
	rm -rf gen/*
	rm -rf tmp/*

#doxygen-ps: ./doc/opalrivet.ps

#./doc/opalrivet.ps: ./doc/opalrivet.tag
#	cd ./doc/latex; \
#	rm -f *.aux *.toc *.idx *.ind *.ilg *.log *.out; \
#	$(DX_LATEX) refman.tex; \
#	$(MAKEINDEX_PATH) refman.idx; \
#	$(DX_LATEX) refman.tex; \
#	countdown=5; \
#	while $(DX_EGREP) 'Rerun (LaTeX|to get cross-references right)' \
#	                  refman.log > /dev/null 2>&1 \
#	   && test $$countdown -gt 0; do \
#	    $(DX_LATEX) refman.tex; \
#	    countdown=`expr $$countdown - 1`; \
#	done; \
#	$(DX_DVIPS) -o ../opalrivet.ps refman.dvi

doxygen-pdf: ./doc/opalrivet.pdf

./doc/opalrivet.pdf: ./doc/opalrivet.tag
	cd ./doc/latex; \
	rm -f *.aux *.toc *.idx *.ind *.ilg *.log *.out; \
	$(DX_PDFLATEX) refman.tex; \
	$(DX_MAKEINDEX) refman.idx; \
	$(DX_PDFLATEX) refman.tex; \
	countdown=5; \
	while $(DX_EGREP) 'Rerun (LaTeX|to get cross-references right)' \
	                  refman.log > /dev/null 2>&1 \
	   && test $$countdown -gt 0; do \
	    $(DX_PDFLATEX) refman.tex; \
	    countdown=`expr $$countdown - 1`; \
	done; \
	mv refman.pdf ../opalrivet.pdf

.PHONY: doxygen-run doxygen-doc $(DX_PS_GOAL) $(DX_PDF_GOAL)

.INTERMEDIATE: doxygen-run $(DX_PS_GOAL) $(DX_PDF_GOAL)

doxygen-run: ./doc/opalrivet.tag

doxygen-doc: doxygen-run $(DX_PS_GOAL) $(DX_PDF_GOAL)

./doc/opalrivet.tag: $(DX_CONFIG) $(pkginclude_HEADERS)
#AV	rm -rf ./doc
	$(DX_ENV) $(DX_DOXYGEN) $(srcdir)/$(DX_CONFIG)

uninstall-local:
		rm $(DESTDIR)$(datadir)/$(PACKAGE)/html/
		-rmdir $(DESTDIR)$(datadir)/$(PACKAGE)/html 
install: install-am install-rootmap install-examples

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
