#ifndef NTUPLE_107J_HH
#define NTUPLE_107J_HH

#include <iostream>
#include "FTypes.h"
#include "hbook.h"

#include "Ntuple.h"

class ntuple_107j : public Ntuple {
private:
  FInteger _irun;
  FInteger _ievnt;
  FInteger _itkmh;
  FInteger _il2mh;
  FInteger _isist;
  FInteger _icvst;
  FInteger _icjst;
  FInteger _iczst;
  FInteger _iebst;
  FInteger _ieest;
  FInteger _nclus;
  FInteger _ntkd02;
  FInteger _iwqqqq;
  FInteger _istg1;
  FInteger _iebal;
  FInteger _icat;
  FReal _ebeam;
  FReal _pspri[4];
  FReal _pspr[4];
  FReal _pgce[4];
  FReal _ephot;
  FReal _efit;
  FReal _pfit;
  FReal _efd;
  FReal _costt;
  FReal _w310;
  FReal _w420;
  FReal _m1234;
  FReal _m1324;
  FReal _m1423;
  FReal _p1234;
  FReal _p1324;
  FReal _p1423;
  FReal _lwqqqq;
  FReal _tdtc;
  FReal _tmadtc;
  FReal _tmidtc;
  FReal _mhdtc;
  FReal _mldtc;
  FReal _btdtc;
  FReal _bwdtc;
  FReal _cpdtc;
  FReal _sdtc;
  FReal _adtc;
  FReal _acpdtc;
  FReal _tdt;
  FReal _tmadt;
  FReal _tmidt;
  FReal _mhdt;
  FReal _mldt;
  FReal _btdt;
  FReal _bwdt;
  FReal _cpdt;
  FReal _sdt;
  FReal _adt;
  FReal _acpdt;
  FReal _tdc;
  FReal _tmadc;
  FReal _tmidc;
  FReal _mhdc;
  FReal _mldc;
  FReal _btdc;
  FReal _bwdc;
  FReal _cpdc;
  FReal _sdc;
  FReal _adc;
  FReal _acpdc;
  FReal _tdmt;
  FReal _tmadmt;
  FReal _tmidmt;
  FReal _mhdmt;
  FReal _mldmt;
  FReal _btdmt;
  FReal _bwdmt;
  FReal _cpdmt;
  FReal _sdmt;
  FReal _admt;
  FReal _acpdmt;
  FInteger _nxjdtc;
  FInteger _nxjdt;
  FInteger _nxjdc;
  FInteger _nxjdmt;
  FInteger _nxjetc;
  FInteger _nxjet;
  FInteger _nxjec;
  FInteger _nxjemt;
  FReal _yddtc[31];
  FReal _yedtc[31];
  FInteger _njcedtc[7];
  FInteger _njcrdtc[7];
  FInteger _njcdtc[31];
  FReal _yddt[31];
  FReal _yedt[31];
  FInteger _njcedt[7];
  FInteger _njcrdt[7];
  FInteger _njcdt[31];
  FReal _yddc[31];
  FReal _yedc[31];
  FInteger _njcedc[7];
  FInteger _njcrdc[7];
  FInteger _njcdc[31];
  FReal _yddmt[31];
  FReal _yedmt[31];
  FInteger _njcedmt[7];
  FInteger _njcrdmt[7];
  FInteger _njcdmt[31];
  FReal _pjt2[4][2];
  FReal _pjt3[4][3];
  FReal _pjt4[4][4];
  FReal _ec2[2];
  FReal _ec3[3];
  FReal _ec4[4];
  FReal _jtc2[2];
  FReal _jtc3[3];
  FReal _jtc4[4];
  FInteger _ijm2[2];
  FInteger _ijm3[3];
  FInteger _ijm4[4];
  FInteger _ntrk;
  FInteger _id02[501];
  FReal _xp[501];
  FReal _yp[501];
  FReal _ptin[501];
  FReal _ptout[501];
  FReal _dedx[501];
  FReal _dded[501];
  FInteger _nhde[501];
  FReal _dp[501];
  FReal _costr[501];
  FInteger _ino;
  FReal _eb;
  FReal _ee[2];
  FReal _zvert;
  FInteger _inttr;
  FInteger _iltr;
  FInteger _itauct;
  FInteger _imcred;
  FInteger _njdcut[2];
  FInteger _ievtyp;
  FInteger _ntrkp;
  FInteger _inonr;
  FInteger _iferid[4];
  FReal _pisr[4];
  FReal _tp;
  FReal _tmap;
  FReal _tmip;
  FReal _mhp;
  FReal _mlp;
  FReal _btp;
  FReal _bwp;
  FReal _cpp;
  FReal _sp;
  FReal _ap;
  FReal _acpp;
  FReal _th;
  FReal _tmah;
  FReal _tmih;
  FReal _mhh;
  FReal _mlh;
  FReal _bth;
  FReal _bwh;
  FReal _cph;
  FReal _sh;
  FReal _ah;
  FReal _acph;
  FInteger _nxjdp;
  FInteger _nxjdh;
  FInteger _nxjep;
  FInteger _nxjeh;
  FReal _ydp[31];
  FReal _yep[31];
  FInteger _njcep[7];
  FInteger _njcrp[7];
  FInteger _njcp[31];
  FReal _ydh[31];
  FReal _yeh[31];
  FInteger _njceh[7];
  FInteger _njcrh[7];
  FInteger _njch[31];
  FReal _pjt2h[4][2];
  FReal _pjt3h[4][3];
  FReal _pjt4h[4][4];
  FInteger _ijm2h[2];
  FInteger _ijm3h[3];
  FInteger _ijm4h[4];
  FInteger _ntrkh;
  FInteger _ntrk2;
  FReal _xph[501];
  FReal _yph[501];
  FReal _ptinh[501];
  FReal _ptouth[501];
  FInteger _iluch[501];
  FInteger _iluc[501];
  FInteger _istrt[501];
public:
  virtual FReal costt() { return _costt; };
  virtual FInteger irun() { return _irun; };
  virtual FInteger ievnt() { return _ievnt; };
  virtual FInteger itkmh() { return _itkmh; };
  virtual FInteger igpmh() { cout << "Error: variable igpmh not available" << endl;return 0;};
  virtual FInteger isist() { return _isist; };
  virtual FInteger icvst() { return _icvst; };
  virtual FInteger icjst() { return _icjst; };
  virtual FInteger iczst() { return _iczst; };
  virtual FInteger iebst() { return _iebst; };
  virtual FInteger ieest() { return _ieest; };
  virtual FInteger istg1() { return _istg1; };
  virtual FInteger ntkd02() { return _ntkd02; };
  virtual FReal ebeam() { return _ebeam; };
  virtual FReal* pgce() { return _pgce; };
  virtual FReal* tvectc() { cout << "Error: variable tvectc not available" << endl;return 0;};
  virtual FInteger il2mh() { return _il2mh; };
  virtual FInteger iwqqqq() { return _iwqqqq; };
  virtual FInteger iwqqln() { cout << "Error: variable iwqqln not available" << endl;return 0;};
  virtual FInteger idqqln() { cout << "Error: variable idqqln not available" << endl;return 0;};
  virtual FInteger iebal() { return _iebal; };
  virtual FInteger icat() { return _icat; };
  virtual FInteger iminrmp() { cout << "Error: variable iminrmp not available" << endl;return 0;};
  virtual FReal* pspri() { return _pspri; };
  virtual FReal* pspr() { return _pspr; };
  virtual FReal ephot() { return _ephot; };
  virtual FReal efit() { return _efit; };
  virtual FReal pfit() { return _pfit; };
  virtual FReal efd() { return _efd; };
  virtual FReal w310() { return _w310; };
  virtual FReal w420() { return _w420; };
  virtual FReal lwqqqq() { return _lwqqqq; };
  virtual FReal lwqqln() { cout << "Error: variable lwqqln not available" << endl;return 0;};
  virtual FReal lwexef0() { cout << "Error: variable lwexef0 not available" << endl;return 0;};
  virtual FReal lwexef1() { cout << "Error: variable lwexef1 not available" << endl;return 0;};
  virtual FReal tdtc() { return _tdtc; };
  virtual FReal tmadtc() { return _tmadtc; };
  virtual FReal tmidtc() { return _tmidtc; };
  virtual FReal mhdtc() { return _mhdtc; };
  virtual FReal mldtc() { return _mldtc; };
  virtual FReal btdtc() { return _btdtc; };
  virtual FReal bwdtc() { return _bwdtc; };
  virtual FReal cpdtc() { return _cpdtc; };
  virtual FReal dpdtc() { cout << "Error: variable dpdtc not available" << endl;return 0;};
  //virtual FReal dpdtc() { return 0;};
  virtual FReal sdtc() { return _sdtc; };
  virtual FReal adtc() { return _adtc; };
  virtual FReal acpdtc() { return _acpdtc; };
  virtual FReal tdt() { return _tdt; };
  virtual FReal tmadt() { return _tmadt; };
  virtual FReal tmidt() { return _tmidt; };
  virtual FReal mhdt() { return _mhdt; };
  virtual FReal mldt() { return _mldt; };
  virtual FReal btdt() { return _btdt; };
  virtual FReal bwdt() { return _bwdt; };
  virtual FReal cpdt() { return _cpdt; };
  virtual FReal dpdt() { cout << "Error: variable dpdt not available" << endl;return 0;};
  //virtual FReal dpdt() { return 0;};
  virtual FReal sdt() { return _sdt; };
  virtual FReal adt() { return _adt; };
  virtual FReal acpdt() { return _acpdt; };
  virtual FReal tdc() { return _tdc; };
  virtual FReal tmadc() { return _tmadc; };
  virtual FReal tmidc() { return _tmidc; };
  virtual FReal mhdc() { return _mhdc; };
  virtual FReal mldc() { return _mldc; };
  virtual FReal btdc() { return _btdc; };
  virtual FReal bwdc() { return _bwdc; };
  virtual FReal cpdc() { return _cpdc; };
  virtual FReal dpdc() { cout << "Error: variable dpdc not available" << endl;return 0;};
  //virtual FReal dpdc() { return 0;};
  virtual FReal sdc() { return _sdc; };
  virtual FReal adc() { return _adc; };
  virtual FReal acpdc() { return _acpdc; };
  virtual FReal tdmt() { return _tdmt; };
  virtual FReal tmadmt() { return _tmadmt; };
  virtual FReal tmidmt() { return _tmidmt; };
  virtual FReal mhdmt() { return _mhdmt; };
  virtual FReal mldmt() { return _mldmt; };
  virtual FReal btdmt() { return _btdmt; };
  virtual FReal bwdmt() { return _bwdmt; };
  virtual FReal cpdmt() { return _cpdmt; };
  virtual FReal dpdmt() { cout << "Error: variable dpdmt not available" << endl;return 0;};
  //virtual FReal dpdmt() { return 0;};
  virtual FReal sdmt() { return _sdmt; };
  virtual FReal admt() { return _admt; };
  virtual FReal acpdmt() { return _acpdmt; };
  virtual FInteger nxjdtc() { return _nxjdtc; };
  virtual FInteger nxjdt() { return _nxjdt; };
  virtual FInteger nxjdc() { return _nxjdc; };
  virtual FInteger nxjdmt() { return _nxjdmt; };
  virtual FInteger nxjetc() { return _nxjetc; };
  virtual FInteger nxjet() { return _nxjet; };
  virtual FInteger nxjec() { return _nxjec; };
  virtual FInteger nxjemt() { return _nxjemt; };
  virtual FInteger nxjctc() { cout << "Error: variable nxjctc not available" << endl;return 0;};
  virtual FInteger nxjct() { cout << "Error: variable nxjct not available" << endl;return 0;};
  virtual FInteger nxjcc() { cout << "Error: variable nxjcc not available" << endl;return 0;};
  virtual FInteger nxjcmt() { cout << "Error: variable nxjcmt not available" << endl;return 0;};
  virtual FReal* yddtc() { return _yddtc; };
  virtual FReal* yedtc() { return _yedtc; };
  virtual FReal* ycdtc() { cout << "Error: variable ycdtc not available" << endl;return 0;};
  virtual FInteger* njcedtc() { return _njcedtc; };
  virtual FInteger* njcrdtc() { return _njcrdtc; };
  virtual FReal* yddt() { return _yddt; };
  virtual FReal* yedt() { return _yedt; };
  virtual FReal* ycdt() { cout << "Error: variable ycdt not available" << endl;return 0;};
  virtual FInteger* njcedt() { return _njcedt; };
  virtual FInteger* njcrdt() { return _njcrdt; };
  virtual FReal* yddc() { return _yddc; };
  virtual FReal* yedc() { return _yedc; };
  virtual FReal* ycdc() { cout << "Error: variable ycdc not available" << endl;return 0;};
  virtual FInteger* njcedc() { return _njcedc; };
  virtual FInteger* njcrdc() { return _njcrdc; };
  virtual FReal* yddmt() { return _yddmt; };
  virtual FReal* yedmt() { return _yedmt; };
  virtual FReal* ycdmt() { cout << "Error: variable ycdmt not available" << endl;return 0;};
  virtual FInteger* njcedmt() { return _njcedmt; };
  virtual FInteger* njcrdmt() { return _njcrdmt; };
  virtual FInteger ntrk() { return _ntrk; };
  virtual FInteger* id02() { return _id02; };
  virtual FReal* dedx() { return _dedx; };
  virtual FReal* dded() { return _dded; };
  virtual FInteger* nhde() { return _nhde; };
  virtual FReal* dp() { return _dp; };
  virtual FReal eb() { return _eb; };
  virtual FReal* ee() { return _ee; };
  virtual FReal zvert() { return _zvert; };
  virtual FInteger inttr() { return _inttr; };
  virtual FInteger iltr() { return _iltr; };
  virtual FInteger itauct() { return _itauct; };
  virtual FReal* ptrk() { cout << "Error: variable ptrk not available" << endl;return 0;};
  virtual FInteger* ichg() { cout << "Error: variable ichg not available" << endl;return 0;};
  virtual FInteger* nhcj() { cout << "Error: variable nhcj not available" << endl;return 0;};
  virtual FReal* z0() { cout << "Error: variable z0 not available" << endl;return 0;};
  virtual FReal* d0() { cout << "Error: variable d0 not available" << endl;return 0;};
  virtual FInteger nmttrk() { cout << "Error: variable nmttrk not available" << endl;return 0;};
  virtual FInteger* imttrk() { cout << "Error: variable imttrk not available" << endl;return 0;};
  virtual FReal* mtscft() { cout << "Error: variable mtscft not available" << endl;return 0;};
  virtual FInteger nclus() { return _nclus; };
  virtual FInteger nmtcls() { cout << "Error: variable nmtcls not available" << endl;return 0;};
  virtual FInteger* imtcls() { cout << "Error: variable imtcls not available" << endl;return 0;};
  virtual FInteger nmtkil() { cout << "Error: variable nmtkil not available" << endl;return 0;};
  virtual FInteger* imtkil() { cout << "Error: variable imtkil not available" << endl;return 0;};
  virtual FReal* pclus() { cout << "Error: variable pclus not available" << endl;return 0;};
  virtual FReal* mtscfc() { cout << "Error: variable mtscfc not available" << endl;return 0;};
  virtual FInteger ioselbt() { cout << "Error: variable ioselbt not available" << endl;return 0;};
  virtual FInteger levslbt() { cout << "Error: variable levslbt not available" << endl;return 0;};
  virtual FInteger nvtxbt() { cout << "Error: variable nvtxbt not available" << endl;return 0;};
  virtual FInteger* ivmulbt() { cout << "Error: variable ivmulbt not available" << endl;return 0;};
  virtual FInteger* nvsigbt() { cout << "Error: variable nvsigbt not available" << endl;return 0;};
  virtual FReal* thrvecbt() { cout << "Error: variable thrvecbt not available" << endl;return 0;};
  virtual FReal* prvtxbt() { cout << "Error: variable prvtxbt not available" << endl;return 0;};
  virtual FReal* vnnbt() { cout << "Error: variable vnnbt not available" << endl;return 0;};
  virtual FReal* vchi2bt() { cout << "Error: variable vchi2bt not available" << endl;return 0;};
  virtual FReal** vtxbt() { cout << "Error: variable vtxbt not available" << endl;return 0;};
  virtual FReal** pvtxbt() { cout << "Error: variable pvtxbt not available" << endl;return 0;};
  virtual FReal* vdlen3bt() { cout << "Error: variable vdlen3bt not available" << endl;return 0;};
  virtual FReal* vderr3bt() { cout << "Error: variable vderr3bt not available" << endl;return 0;};
  virtual FInteger ievtyp() { return _ievtyp; };
  virtual FInteger inonr() { return _inonr; };
  virtual FReal* pisr() { return _pisr; };
  virtual FInteger nprimf() { cout << "Error: variable nprimf not available" << endl;return 0;};
  virtual FInteger* iferid() { return _iferid; };
  virtual FReal** primf() { cout << "Error: variable primf not available" << endl;return 0;};
  virtual FReal tp() { return _tp; };
  virtual FReal tmap() { return _tmap; };
  virtual FReal tmip() { return _tmip; };
  virtual FReal mhp() { return _mhp; };
  virtual FReal mlp() { return _mlp; };
  virtual FReal btp() { return _btp; };
  virtual FReal bwp() { return _bwp; };
  virtual FReal cpp() { return _cpp; };
  virtual FReal dpp() { cout << "Error: variable dpp not available" << endl;return 0;};
  //virtual FReal dpp() { return 0;};
  virtual FReal sp() { return _sp; };
  virtual FReal ap() { return _ap; };
  virtual FReal acpp() { return _acpp; };
  virtual FReal th() { return _th; };
  virtual FReal tmah() { return _tmah; };
  virtual FReal tmih() { return _tmih; };
  virtual FReal mhh() { return _mhh; };
  virtual FReal mlh() { return _mlh; };
  virtual FReal bth() { return _bth; };
  virtual FReal bwh() { return _bwh; };
  virtual FReal cph() { return _cph; };
  virtual FReal dph() { cout << "Error: variable dph not available" << endl;return 0;};
  //virtual FReal dph() { return 0;};
  virtual FReal sh() { return _sh; };
  virtual FReal ah() { return _ah; };
  virtual FReal acph() { return _acph; };
  virtual FInteger nxjdp() { return _nxjdp; };
  virtual FInteger nxjdh() { return _nxjdh; };
  virtual FInteger nxjep() { return _nxjep; };
  virtual FInteger nxjeh() { return _nxjeh; };
  virtual FInteger nxjcp() { cout << "Error: variable nxjcp not available" << endl;return 0;};
  virtual FInteger nxjch() { cout << "Error: variable nxjch not available" << endl;return 0;};
  virtual FReal* ydp() { return _ydp; };
  virtual FReal* yep() { return _yep; };
  virtual FReal* ycp() { cout << "Error: variable ycp not available" << endl;return 0;};
  virtual FInteger* njcep() { return _njcep; };
  virtual FInteger* njcrp() { return _njcrp; };
  virtual FReal* ydh() { return _ydh; };
  virtual FReal* yeh() { return _yeh; };
  virtual FReal* ych() { cout << "Error: variable ych not available" << endl;return 0;};
  virtual FInteger* njceh() { return _njceh; };
  virtual FInteger* njcrh() { return _njcrh; };
  virtual FInteger ntrkp() { return _ntrkp; };
  virtual FInteger* ilucp() { cout << "Error: variable ilucp not available" << endl;return 0;};
  virtual FReal** ptrkp() { cout << "Error: variable ptrkp not available" << endl;return 0;};
  virtual FInteger ntrkh() { return _ntrkh; };
  virtual FInteger ntrk2() { return _ntrk2; };
  virtual FReal** ptrkh() { cout << "Error: variable ptrkh not available" << endl;return 0;};
  virtual FInteger* iluch() { return _iluch; };
  virtual FInteger* iluc() { return _iluc; };
  virtual FInteger* istrt() { return _istrt; };
  virtual FInteger* ichgh() { cout << "Error: variable ichgh not available" << endl;return 0;};

  virtual void DAInit( FInteger ID );
  virtual void MCInit( FInteger ID );
ClassDef(ntuple_107j,0)
};


#endif
