#ifndef NTUPLE_HH
#define NTUPLE_HH

#include "FTypes.h"
#include <TObject.h>

class Ntuple : public TObject
{

public:

    Ntuple() {};
    virtual ~Ntuple() {};

    virtual void NTinit( FInteger ID, bool isMC );
    virtual void NTclean( FInteger ID );
    virtual void DAInit( FInteger ID ) = 0;
    virtual void MCInit( FInteger ID ) = 0;

    virtual void getmt( FReal ptrack[][4], FInteger maxtrk, FInteger & ntrack );
    virtual void gettc( FReal ptrack[][4], FInteger maxtrk, FInteger & ntrack );
    virtual void gettrk( FReal ptrack[][4], FInteger maxtrk, FInteger & ntrack );
    virtual void getcls( FReal ptrack[][4], FInteger maxtrk, FInteger & ntrack,
                         FInteger ioff=0 );

    virtual FReal costt() = 0;
    virtual FInteger irun() = 0;
    virtual FInteger ievnt() = 0;
    virtual FInteger itkmh() = 0;
    virtual FInteger igpmh() = 0;
    virtual FInteger isist() = 0;
    virtual FInteger icvst() = 0;
    virtual FInteger icjst() = 0;
    virtual FInteger iczst() = 0;
    virtual FInteger iebst() = 0;
    virtual FInteger ieest() = 0;
    virtual FInteger istg1() = 0;
    virtual FInteger ntkd02() = 0;
    virtual FReal ebeam() = 0;
    virtual FReal* pgce() = 0;
    virtual FReal* tvectc() = 0;
    virtual FInteger il2mh() = 0;
    virtual FInteger iwqqqq() = 0;
    virtual FInteger iwqqln() = 0;
    virtual FInteger idqqln() = 0;
    virtual FInteger iebal() = 0;
    virtual FInteger icat() = 0;
    virtual FInteger iminrmp() = 0;
    virtual FReal* pspri() = 0;
    virtual FReal* pspr() = 0;
    virtual FReal ephot() = 0;
    virtual FReal efit() = 0;
    virtual FReal pfit() = 0;
    virtual FReal efd() = 0;
    virtual FReal w310() = 0;
    virtual FReal w420() = 0;
    virtual FReal lwqqqq() = 0;
    virtual FReal lwqqln() = 0;
    virtual FReal lwexef0() = 0;
    virtual FReal lwexef1() = 0;
    virtual FReal tdtc() = 0;
    virtual FReal tmadtc() = 0;
    virtual FReal tmidtc() = 0;
    virtual FReal mhdtc() = 0;
    virtual FReal mldtc() = 0;
    virtual FReal btdtc() = 0;
    virtual FReal bwdtc() = 0;
    virtual FReal cpdtc() = 0;
    virtual FReal dpdtc() = 0;
    virtual FReal sdtc() = 0;
    virtual FReal adtc() = 0;
    virtual FReal acpdtc() = 0;
    virtual FReal tdt() = 0;
    virtual FReal tmadt() = 0;
    virtual FReal tmidt() = 0;
    virtual FReal mhdt() = 0;
    virtual FReal mldt() = 0;
    virtual FReal btdt() = 0;
    virtual FReal bwdt() = 0;
    virtual FReal cpdt() = 0;
    virtual FReal dpdt() = 0;
    virtual FReal sdt() = 0;
    virtual FReal adt() = 0;
    virtual FReal acpdt() = 0;
    virtual FReal tdc() = 0;
    virtual FReal tmadc() = 0;
    virtual FReal tmidc() = 0;
    virtual FReal mhdc() = 0;
    virtual FReal mldc() = 0;
    virtual FReal btdc() = 0;
    virtual FReal bwdc() = 0;
    virtual FReal cpdc() = 0;
    virtual FReal dpdc() = 0;
    virtual FReal sdc() = 0;
    virtual FReal adc() = 0;
    virtual FReal acpdc() = 0;
    virtual FReal tdmt() = 0;
    virtual FReal tmadmt() = 0;
    virtual FReal tmidmt() = 0;
    virtual FReal mhdmt() = 0;
    virtual FReal mldmt() = 0;
    virtual FReal btdmt() = 0;
    virtual FReal bwdmt() = 0;
    virtual FReal cpdmt() = 0;
    virtual FReal dpdmt() = 0;
    virtual FReal sdmt() = 0;
    virtual FReal admt() = 0;
    virtual FReal acpdmt() = 0;
    virtual FInteger nxjdtc() = 0;
    virtual FInteger nxjdt() = 0;
    virtual FInteger nxjdc() = 0;
    virtual FInteger nxjdmt() = 0;
    virtual FInteger nxjetc() = 0;
    virtual FInteger nxjet() = 0;
    virtual FInteger nxjec() = 0;
    virtual FInteger nxjemt() = 0;
    virtual FInteger nxjctc() = 0;
    virtual FInteger nxjct() = 0;
    virtual FInteger nxjcc() = 0;
    virtual FInteger nxjcmt() = 0;
    virtual FReal* yddtc() = 0;
    virtual FReal* yedtc() = 0;
    virtual FReal* ycdtc() = 0;
    virtual FInteger* njcedtc() = 0;
    virtual FInteger* njcrdtc() = 0;
    virtual FReal* yddt() = 0;
    virtual FReal* yedt() = 0;
    virtual FReal* ycdt() = 0;
    virtual FInteger* njcedt() = 0;
    virtual FInteger* njcrdt() = 0;
    virtual FReal* yddc() = 0;
    virtual FReal* yedc() = 0;
    virtual FReal* ycdc() = 0;
    virtual FInteger* njcedc() = 0;
    virtual FInteger* njcrdc() = 0;
    virtual FReal* yddmt() = 0;
    virtual FReal* yedmt() = 0;
    virtual FReal* ycdmt() = 0;
    virtual FInteger* njcedmt() = 0;
    virtual FInteger* njcrdmt() = 0;
    virtual FInteger ntrk() = 0;
    virtual FInteger* id02() = 0;
    virtual FReal* dedx() = 0;
    virtual FReal* dded() = 0;
    virtual FInteger* nhde() = 0;
    virtual FReal* dp() = 0;
    virtual FReal eb() = 0;
    virtual FReal* ee() = 0;
    virtual FReal zvert() = 0;
    virtual FInteger inttr() = 0;
    virtual FInteger iltr() = 0;
    virtual FInteger itauct() = 0;
    virtual FReal* ptrk() = 0;
    virtual FInteger* ichg() = 0;
    virtual FInteger* nhcj() = 0;
    virtual FReal* z0() = 0;
    virtual FReal* d0() = 0;
    virtual FInteger nmttrk() = 0;
    virtual FInteger* imttrk() = 0;
    virtual FReal* mtscft() = 0;
    virtual FInteger nclus() = 0;
    virtual FInteger nmtcls() = 0;
    virtual FInteger* imtcls() = 0;
    virtual FInteger nmtkil() = 0;
    virtual FInteger* imtkil() = 0;
    virtual FReal* pclus() = 0;
    virtual FReal* mtscfc() = 0;
    virtual FInteger ioselbt() = 0;
    virtual FInteger levslbt() = 0;
    virtual FInteger nvtxbt() = 0;
    virtual FInteger* ivmulbt() = 0;
    virtual FInteger* nvsigbt() = 0;
    virtual FReal* thrvecbt() = 0;
    virtual FReal* prvtxbt() = 0;
    virtual FReal* vnnbt() = 0;
    virtual FReal* vchi2bt() = 0;
    virtual FReal** vtxbt() = 0;
    virtual FReal** pvtxbt() = 0;
    virtual FReal* vdlen3bt() = 0;
    virtual FReal* vderr3bt() = 0;
    virtual FInteger ievtyp() = 0;
    virtual FInteger inonr() = 0;
    virtual FReal* pisr() = 0;
    virtual FInteger nprimf() = 0;
    virtual FInteger* iferid() = 0;
    virtual FReal** primf() = 0;
    virtual FReal tp() = 0;
    virtual FReal tmap() = 0;
    virtual FReal tmip() = 0;
    virtual FReal mhp() = 0;
    virtual FReal mlp() = 0;
    virtual FReal btp() = 0;
    virtual FReal bwp() = 0;
    virtual FReal cpp() = 0;
    virtual FReal dpp() = 0;
    virtual FReal sp() = 0;
    virtual FReal ap() = 0;
    virtual FReal acpp() = 0;
    virtual FReal th() = 0;
    virtual FReal tmah() = 0;
    virtual FReal tmih() = 0;
    virtual FReal mhh() = 0;
    virtual FReal mlh() = 0;
    virtual FReal bth() = 0;
    virtual FReal bwh() = 0;
    virtual FReal cph() = 0;
    virtual FReal dph() = 0;
    virtual FReal sh() = 0;
    virtual FReal ah() = 0;
    virtual FReal acph() = 0;
    virtual FInteger nxjdp() = 0;
    virtual FInteger nxjdh() = 0;
    virtual FInteger nxjep() = 0;
    virtual FInteger nxjeh() = 0;
    virtual FInteger nxjcp() = 0;
    virtual FInteger nxjch() = 0;
    virtual FReal* ydp() = 0;
    virtual FReal* yep() = 0;
    virtual FReal* ycp() = 0;
    virtual FInteger* njcep() = 0;
    virtual FInteger* njcrp() = 0;
    virtual FReal* ydh() = 0;
    virtual FReal* yeh() = 0;
    virtual FReal* ych() = 0;
    virtual FInteger* njceh() = 0;
    virtual FInteger* njcrh() = 0;
    virtual FInteger ntrkp() = 0;
    virtual FInteger* ilucp() = 0;
    virtual FReal** ptrkp() = 0;
    virtual FInteger ntrkh() = 0;
    virtual FInteger ntrk2() = 0;
    virtual FReal** ptrkh() = 0;
    virtual FInteger* iluch() = 0;
    virtual FInteger* iluc() = 0;
    virtual FInteger* istrt() = 0;
    virtual FInteger* ichgh() = 0;
ClassDef(Ntuple,0)

};

#endif
